dist: xenial
language: python
python:
 - '3.5'
 - '3.6'
 - '3.7'
install:
 - pip install flake8 flake8-import-order flake8-builtins
before_script:
 - mv .travis/system.dic.test tests/resources/system.dic
script:
 - ./scripts/format.sh
 - python -m unittest discover tests
