dist: xenial
language: python
python:
 - '3.5'
 - '3.6'
 - '3.7'
install:
 - pip install flake8
before_script:
 - cp .travis/system.dic.test tests/resources
script:
 - ./scripts/format.sh
 - python -m unittest discover tests
